version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_etudiants
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: etudiants_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: jakartaee_app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
